### ISSUE TITLE
Break apart test cases

### ISSUE THREAD

**Issue by bwolatz** [axnasim/csci4900#12]
In your test case file, you try to do three things. The reader is to assume that all three passed.

In unit tests, make sure to test things one at a time, so have three unit tests, one that stores the jar package, one that tests the oneshot, and one that creates the transitive tree structure.

**Comment by axnasim** [comment]
The test for oneshot will be in separate.
The other tests for tree structure and jar file will still be in same file and will be run in same location as pom.xl
