### ISSUE TITLE
Using the relationship tree

### ISSUE THREAD

**Issue by bwolatz** [axnasim/csci4900#14]
The graphml output hold all the jar relationship information. However, in looking at your code, it is not apparent how the graphml is used. It doesn't get saved in your current working directory (the temp folder), and it doesn't appear to be used or referenced. How is it used to generate relationship information for a DoSOCS database entry (and finally an SPDX document)?

**Comment by axnasim** [comment]
Output for jar relationship will be text file. And is used to parse the 3 level dependencies to another text file.
