### ISSUE TITLE
User case

### ISSUE THREAD

**Issue by axnasim** [axnasim/csci4900#6]
[pom.docx](https://github.com/axnasim/csci4900/files/176553/pom.docx)

**Comment by axnasim** [comment]
[Mockup System.txt](https://github.com/axnasim/csci4900/files/176561/Mockup.System.txt)

**Comment by Qais944** [comment]
Use cases should contain:
• Title
• Primary Actor
• Goal in Context
• Stakeholders and Interests
• Preconditions
• Main Success Scenario
• Failed End Conditions
• Trigger
• Notes
